INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_AUTH_TM_USER_AUTH', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_EBCCVAL_TR_EBCC_VALIDATION_D', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_EBCCVAL_TR_EBCC_VALIDATION_H', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_FINDING_TR_FINDING', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_INS_TR_BLOCK_INSPECTION_D', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_INS_TR_BLOCK_INSPECTION_H', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_INS_TR_INSPECTION_GENBA', null, null );
INSERT INTO MOBILE_INSPECTION.TM_KAFKA_PAYLOADS( TOPIC_NAME, OFFSET, EXECUTE_DATE ) VALUES( 'INS_MSA_INS_TR_TRACK_INSPECTION', null, null );
